### ISSUE TITLE
Alternatives for positional arrays

### ISSUE THREAD

**Issue by BenShelton** [alex-stlrv/math-for-fun#1]
https://github.com/alex-stlrv/math-for-fun/blob/be45b03d48e90211d02e9479e41f7aee4a6959f9/math.js#L30-L31

This is a clever way to only use indexes you haven't used before. Here are some alternative ways to accomplish the same that may be interesting to try:

1. Keep your "master array" and then have another copy for what you are currently using. When starting a new games then copy the array and each time you use one then splice it. Something like:
```ts
const originalImages = [image1, image2, image3]
// different ways to copy when resetting
const currentGameImages = [...originalImages]
const currentGameImages = originalImages.slice()
// remove an index
const index = getRandomInt(currentGameImages.length)
const [foundImage] = currentGameImages.splice(index, 1)
```

2. When starting a new game then create a shuffled version of the array so you can just `pop` each one at a time. There are a few ways to shuffle arrays so I won't go into detail on those.

**Comment by alex-stlrv** [comment]
Thank you so much @BenShelton! I have used your suggestions in refactoring how I approach image arrays and I also how I handle the answer display (trying not to brute force anything anymore)
