### ISSUE TITLE
Split utility function into separate file

### ISSUE THREAD

**Issue by BenShelton** [alex-stlrv/math-for-fun#3]
https://github.com/alex-stlrv/math-for-fun/blob/be45b03d48e90211d02e9479e41f7aee4a6959f9/math.js#L57-L59

This utility function is a good example of something that could be extracted into another JS file. It's standalone, it doesn't care about anything around it, and it's pure (it doesn't change state of variables outside of the function, including those that are passed by arguments)

In vanilla old-school JS you can move this to another `.js` file, add another script tag to your `index.html` to reference that new file, and you will be able to still use that function. All the scripts will be able to access variables from other scripts without specifically referencing them as you may be more familiar with.

You could also try using `module` type script imports by adding the `type="module"` param to them in your `index.html`. See here for more details: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by alex-stlrv** [comment]
Thank you so much @BenShelton! This is now working with modules. Also thank you for providing informative readings
